filter-by-commitish: false
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
prerelease-identifier: 'test'
version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
    - 'enhancement'
  patch:
    labels:
    - 'auto-update'
    - 'patch'
    - 'fix'
    - 'bugfix'
    - 'bug'
    - 'hotfix'
    - 'no-release'
  default: 'minor'

categories:
- title: 'ðŸš€ Enhancements'
  labels:
  - 'enhancement'
  - 'patch'
- title: 'ðŸ› Bug Fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'hotfix'
- title: 'ðŸ¤– Automatic Updates'
  labels:
  - 'auto-update'

change-template: "SKIP CHANGES FOR FEATURE RELEASES"
template: |
  ## ðŸš€ Feature Preview Release
  
  This is a **feature preview** based on an open pull request. It is intended for testing artifacts and validating functionality before the feature is merged.
  
  > [!WARNING]
  > This release is temporary and may be removed at any time without notice.
