# See https://runs-on.com/configuration/repo-config/

# This file is used to define the baseline runs-on configuration for the organization.

# See https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
# for comparison to GitHub hosted runners.
# The short story is that GitHub hosted PUBLIC runners generally have:
#    4 CPU, 16 GiB Ram, and 14 GB SSD disk
# While GitHub hosted PRIVATE runners generally have:
#    2 CPU, 7 GiB Ram, and 14 GB SSD disk

# Note that the sizes reflect that Cloud Posse does not do heavy lifting on the self-hosted runners.
# A Cloud Posse client might need much more CPU and Memory for their runners,
# for example if they were running Node.js, compiling source, processing video, or doing data analysis.

# Also note, you cannot use extras: ["s3-cache"] unless you also start with
# a `runs-on/action` step, or else actions/upload-artifact and related steps will fail.
# So we do not set extras: ["s3-cache"] here. Set "extras=s3-cache" in the workflow file instead,
# when you have a `runs-on/action` step.

runners:
  default: &default
    image: ubuntu22-full-x64
    family:
      # List all instance types that support encryption in transit and are x86_64 architecture
      # and format as YAML array with wildcard suffix:
      #  aws ec2 describe-instance-types \
      #  --filters \
      #  Name=network-info.encryption-in-transit-supported,Values=true \
      #  Name=processor-info.supported-architecture,Values=x86_64 \
      #  --query "InstanceTypes[*].[InstanceType]" \
      #  --output text | cut -f 1 -d. | sort | uniq | awk '{print "      - " $0 ".*"}'
      - c5a.*
      - c5ad.*
      - c5n.*
      - c6a.*
      - c6i.*
      - c6id.*
      - c6in.*
      - c7a.*
      - c7i.*
      - c7i-flex.*
      - d3.*
      - g4ad.*
      - g4dn.*
      - g5.*
      - g6.*
      - g6e.*
      - gr6.*
      - hpc6a.*
      - hpc6id.*
      - hpc7a.*
      - i3en.*
      - i4i.*
      - i7ie.*
      - inf1.*
      - inf2.*
      - m5dn.*
      - m5n.*
      - m5zn.*
      - m6a.*
      - m6i.*
      - m6id.*
      - m6idn.*
      - m6in.*
      - m7a.*
      - m7i.*
      - m7i-flex.*
      - p4d.*
      - p5.*
      - p5e.*
      - p5en.*
      - r5dn.*
      - r5n.*
      - r6a.*
      - r6i.*
      - r6id.*
      - r6idn.*
      - r6in.*
      - r7a.*
      - r7i.*
      - r7iz.*
      - trn1.*
      - trn1n.*
      - trn2.*
      - u-12tb1.*
      - u-3tb1.*
      - u-6tb1.*
      - u-9tb1.*
      - x2idn.*
      - x2iedn.*
    cpu: [2, 16]
    ram: [2, 64]
    disk: default
    spot: price-capacity-optimized
    retry: when-interrupted
    private: true
    ssh: false
    tags:
      - "gha-runner:runs-on/default"

  common: *default
  small: *default

  default-amd64: *default
  common-amd64: *default
  small-amd64: *default

  medium: &medium
    <<: *default
    cpu: [2, 32]
    ram: [8, 64]
    tags:
      - "gha-runner:runs-on/medium"

  medium-amd64: *medium

  # This runner is used for running terraform commands
  # Terraform is generally I/O bound and does not need a lot of CPU, but
  # experience has shown that a single "apply" can easily exceed 4GB of memory.
  terraform:
    <<: *default
    cpu: [2, 32]
    ram: [8, 64]
    tags:
      - "gha-runner:runs-on/terraform"

  large: &large
      <<: *default
      cpu: [4, 64]
      ram: [16, 128]
      disk: large
      tags:
        - "gha-runner:runs-on/large"

  large-amd64: *large

  default-arm64: &default-arm64
    <<: *default
    image: ubuntu22-full-arm64
    tags:
      - "gha-runner:runs-on/default-arm64"
      # List all instance types that support encryption in transit and are arm64 architecture
      # and format as YAML array with wildcard suffix:
      #  aws ec2 describe-instance-types \
      #  --filters \
      #  Name=network-info.encryption-in-transit-supported,Values=true \
      #  Name=processor-info.supported-architecture,Values=arm64 \
      #  --query "InstanceTypes[*].[InstanceType]" \
      #  --output text | cut -f 1 -d. | sort | uniq | awk '{print "      - " $0 ".*"}'
    family:
      - c6gn.*
      - c7g.*
      - c7gd.*
      - c7gn.*
      - c8g.*
      - i4g.*
      - im4gn.*
      - is4gen.*
      - m7g.*
      - m7gd.*
      - m8g.*
      - r7g.*
      - r7gd.*
      - r8g.*

  small-arm64: *default-arm64
  packages-arm64: *default-arm64

  medium-arm64:
    <<: *default-arm64
    cpu: [2, 32]
    ram: [8, 64]
    tags:
      - "gha-runner:runs-on/medium-arm64"

  large-arm64:
    <<: *default-arm64
    cpu: [4, 64]
    ram: [16, 128]
    disk: large
    tags:
      - "gha-runner:runs-on/large-arm64"

