name: Main branch
on:
  push:
    branches: [ $default-branch ]

permissions:
  contents: write

jobs:
  default:
    uses: cloudposse/github-actions-workflows/.github/workflows/github-composite-action-main-branch.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
