name: Feature branch
on:
  pull_request:
    branches: [ $default-branch ]
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]

jobs:
  default:
    uses: cloudposse/github-actions-workflows/.github/workflows/github-composite-action-feature-branch.yml@main