name: Bleeding edge
on:
  push:
    branches: [ $default-branch ]

permissions:
  contents: write

jobs:
  default:
    uses: cloudposse/github-actions-workflows/.github/workflows/github-composite-action-bleeding-edge.yml@main
