name: Release
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  perform:
    uses: cloudposse/.github/.github/workflows/shared-release-branches.yml@main
    secrets: inherit
