name: Lint

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  lint-readme:
    name: Lint README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cloudposse/build-harness@master
        with:
          entrypoint: /usr/bin/make
          args: readme/lint
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master


