name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  lint-readme:
    name: README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cloudposse/build-harness@markdown-lint-changes
        with:
          entrypoint: /usr/bin/make
          args: readme/lint
  super-linter:
    name: Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master


