name: CI - Readme
on:
  workflow_call:
    inputs:
      ref:
        description: "Checkout ref"
        type: string
        required: false
        default: ${{ github.ref_name }}
      repository:
        description: "Checkout repository"
        type: string
        required: false
        default: ${{ github.repository }}
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  validate:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    name: "Readme"
    environment: release
    steps:
      - uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          fetch-depth: 0
          token: ${{ steps.github-app.outputs.token }}

      - uses: cloudposse-github-actions/readme@use-atmos-to-generate-readme
        with:
          token: ${{ steps.github-app.outputs.token }}
          readme_enabled: true
          banner_enabled: true
          validate_readme: true
          commit_method: 'commit'
          commit_push_options: '--force-with-lease'
