name: "Shared github action workflow"

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      tests-prefix:
        description: "Workflows file name prefix to run as tests"
        required: false
        type: string
        default: 'test-*'
      publish:
        description: "Whether to publish a new release immediately"
        required: false
        default: "true"
        type: string
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@shared-workflows
    name: "Readme"
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit

  ci-gha:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-github-action.yml@main
    name: "CI"
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      ref: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}
      tests-prefix: ${{ inputs.tests-prefix }}

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ ci-gha, ci-readme ]

  release:
    needs: [ ci ]
    name: "Release"
    if: ${{ github.event_name == 'push' }}
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    with:
      publish: ${{ inputs.publish }}
    secrets: inherit
