name: CI - Codeowners
on:
  workflow_call:
    inputs:
      is_fork:
        description: "Run workflow in fork mode (decreased permissions and features)"
        type: boolean
        required: true
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  syntax:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    name: Validate Codeowners (syntax)
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: mszostok/codeowners-validator@2f478ec3b2c8a321d46fca773f6285a447234f6a # v0.7.1
        # Pull request from a fork
        name: "Validate CODEOWNERS"
        with:
          checks: "syntax,duppatterns"
          owner_checker_allow_unowned_patterns: "false"

  owners:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    name: Validate Codeowners (owners)
    if: ${{ false && ! inputs.is_fork }}
    environment: release    
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: github-app
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
          
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.github-app.outputs.token }}

      - uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f # v0.7.4
        # Main branch / Pull request from the same repo
        name: "Validate CODEOWNERS"
        with:
          # For now, remove "files" check to allow CODEOWNERS to specify non-existent
          # files so we can use the same CODEOWNERS file for Terraform and non-Terraform repos
          #   checks: "files,syntax,owners,duppatterns"
          checks: "owners"
          owner_checker_allow_unowned_patterns: "false"
          # Admin GitHub access token is required only if the `owners` check is enabled
          github_access_token: ${{ steps.github-app.outputs.token }}
          
