name: "Validate Codeowners"
on:
  pull_request_target:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-validate-codeowners@main
      with:
        token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
