name: "validate-codeowners"
on:
  pull_request_target:
  workflow_dispatch:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-validate-codeowners@main
      with:
        token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
